use_frameworks!

platform :ios, '10.0'

target 'TestFramework_Example' do
  pod 'TestFramework', :path => '../'

  target 'TestFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
